package com.planthings.api.intelligence.model;

public enum AiMessageBlockType {
  MARKDOWN,
  QUESTION,
  PLAN_PROPOSAL,
  CARD_BATCH_PROPOSAL,
  MEMBER_INVITE_PROPOSAL,
  FILE_ATTACH_PROPOSAL,
  PLAN_REFERENCE,
  CARD_REFERENCE,
  FILE_REFERENCE,
  MEMBER_REFERENCE,
  INBOX_REFERENCE,
  GITHUB_COMMIT_REFERENCE,
  GITHUB_PULL_REQUEST_REFERENCE,
  TOOL_RUN_SUMMARY
}
